# .github/workflows/test-paper.yml
name: CI & Benchmark

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  benchmark:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build and run benchmarks
        run: |
          npm run build
          node benchmark.js examples/angular-bad-code.ts > bad-results.txt
          node benchmark.js examples/angular-good-code.ts > good-results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            bad-results.txt
            good-results.txt

  verify-results:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Download benchmark results
        uses: actions/download-artifact@v3
        with:
          name: benchmark-results

      - name: Display results
        run: |
          echo "📄 BAD CODE RESULTS:"
          cat bad-results.txt
          echo ""
          echo "📄 GOOD CODE RESULTS:"
          cat good-results.txt

      - name: Validate output (basic check)
        run: |
          if ! grep -q "Benchmarking" bad-results.txt; then
            echo "::error::No valid output in bad-results.txt"
            exit 1
          fi
          if ! grep -q "Benchmarking" good-results.txt; then
            echo "::error::No valid output in good-results.txt"
            exit 1
          fi